#!/bin/sh -e

#  From: $return_address
#  To: $cia_address
#  Content-type: text/xml
#  Subject: DeliverXML
#  
#  <message>
#      <generator>
#          <name>BitKeeper CIA Bot client shell script</name>
#          <version>1.0</version>
#      </generator>
#      <source>
#          <project>$project_name</project>
#          <module>$module</module>
#          <branch>$tag</branch>
#      </source>
#      <body>
#          <commit>
#              <revision>$REV</revision>
#              <author>$author</author>
#              <files>$files</files>
#              <log>$log</log>
#          </commit>
#      </body>
#  </message>

url="http://cvs.linuxcnc.org/cvs"

echo "From: EMC CVS server <cvs-adm@cvs.linuxcnc.org>"
#echo "To: chris@timeguy.com"
echo "To: cia@cia.navi.cx"
echo "Content-type: text/xml"
echo "Subject: DeliverXML"
echo

tag=HEAD

while read i; do 
  case "$i" in
  Tag:*)
    tag="${i#Tag: }"
  ;;
  esac
done

# split at spaces
set -- $*

if [ x$2 = x- ]; then
  echo "New directory $1"
  exit 0
fi

dir="$1"; shift

files=""
for i; do
  files="$files<file>${i%%,*}</file>"
done

rlog() {
  now=no
  /bin/rlog -r"$1" /cvs/"$2",v |while read line; do
    case "$line" in 
    ==========*)
    ;;
    ----------*)
    ;;
    date:\ *)
      author="$line"
      author="${author#*author: }"
      author="${author%%;*}"
      echo "   <author>$author</author>"
      echo -n "   <log>"
      now=yes
    ;;
    *)
      [ $now = yes ] && echo "$line"
    esac
  done
  echo "   </log>"
}

i="$1"
file=${i%%,*}

before=${i%,*}
before=${before#*,}

after=${i##*,}

echo "<message>"
echo " <generator>"
echo "  <name>EMC CIA script</name>"
echo "  <version>1.0</version>"
echo " </generator>"
echo " <source>"
echo "  <project>EMC</project>"
echo "  <module>$dir</module>"
echo "  <branch>$tag</branch>"
echo " </source>"
echo " <body>"
echo "  <commit>"
#echo "   <revision>$after</revision>"
echo "   <files>$files</files>"
rlog "$after" "$dir/$file"
echo "  </commit>"
echo " </body>"
echo "</message>"
echo

